MainEmbed:
  Title: Download Panel
  Description: Click the button below to download.
Buttons:
  - Name: Download
    Emoji: 游닌
    CustomId: download_file
    URL: test
  - Name: Download2
    Emoji: 游닌
    CustomId: download_file2
    URL: https://example.com/download2
  - Name: Download3
    Emoji: 游닌
    CustomId: download_file3
    URL: https://www.google.com
    Style: Link
  - Name: Download4
    Emoji: 游닌
    CustomId: download_file4
    URL: https://example.com/download4
  - Name: External Link
    Emoji: 游댕
    CustomId: external_link
    URL: https://example.com
    Style: Link
